- name: Demo on load another file
  hosts: all
  tasks:
  - name: Print Hello World
    ansible.builtin.debug:
     msg: Hello World

  - name: Include 03.yml having hello universe
    ansible.builtin.include_tasks:
     file: 3.yml
